import React from 'react'

export const SCPage = [
            <p key  = '1'>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris convallis lorem at varius tempor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed convallis, libero vitae tempor pretium, massa sapien sagittis nisl, sit amet tempus diam turpis eu risus. Proin ut sapien quam. Vestibulum et luctus ex, in auctor mauris. Praesent at ipsum at arcu imperdiet blandit a vel tortor. Donec nec tellus eu nibh consequat dapibus sed dapibus risus. Morbi id suscipit tortor. Sed fringilla metus non ante facilisis, non viverra sem molestie. Quisque volutpat tempus sollicitudin. Nulla sollicitudin enim nisl, eu condimentum libero placerat sit amet. Suspendisse commodo, est in cursus maximus, lorem lacus aliquet magna, sit amet semper magna sem ullamcorper lacus. Donec id odio augue. Sed dictum magna dolor, eget sodales ipsum condimentum pharetra. Mauris id mauris faucibus, commodo dolor vel, mollis sem.
            </p>,
            <p key  = '2'>
Quisque a semper libero. Suspendisse sit amet pulvinar ante, eu sagittis nunc. Donec dictum elementum enim, eget mattis tellus aliquam eget. Nullam efficitur ante diam, non ultrices risus accumsan faucibus. Proin molestie lorem id sodales fermentum. Cras pellentesque ante id molestie luctus. Curabitur malesuada ante et purus feugiat dignissim. Fusce quis scelerisque justo, quis commodo libero. Maecenas scelerisque dapibus ex vel porta. In hendrerit quis sem vitae dapibus. Pellentesque luctus justo ut odio consectetur, et faucibus nibh pretium. Vivamus sit amet eros a dui rhoncus sollicitudin. Cras ultricies urna vel accumsan posuere. Cras ac erat lorem.
    </p>,
    <p key  = '3'>
Maecenas sodales est et lectus auctor, vitae luctus nunc aliquet. Etiam et scelerisque odio, in consectetur nulla. Proin quis est in arcu finibus rhoncus et non felis. Fusce facilisis varius turpis sit amet tempor. Vestibulum ornare tellus metus, luctus ultrices elit facilisis id. Vivamus fringilla, mauris vitae accumsan viverra, arcu ligula tempus est, sed porta sapien libero vel augue. Quisque tristique nec ipsum ac interdum.
    </p>,
    <p key  = '4'>
Phasellus gravida, diam non maximus volutpat, est velit bibendum urna, ac rhoncus nunc orci non tellus. Suspendisse id ligula a est tempus pretium ut et velit. Donec efficitur posuere turpis, sit amet gravida tellus vulputate ac. Phasellus luctus ante ut leo dapibus, rhoncus molestie orci tincidunt. Mauris in condimentum erat, quis tincidunt ipsum. Aliquam faucibus libero sit amet sem semper rutrum rhoncus et diam. Praesent et volutpat lorem. Aliquam ex nulla, pharetra ut augue sagittis, interdum malesuada nunc. Quisque rutrum ex non nulla suscipit congue. Phasellus ornare, tellus quis scelerisque rhoncus, risus est molestie massa, non imperdiet enim arcu eu ex. Nam viverra dictum lorem vitae convallis. Ut porta lorem at massa pellentesque lobortis. Mauris suscipit lectus at justo pharetra, interdum pulvinar nunc luctus. Maecenas non scelerisque nunc.
    </p>,
    <p key  = '5'>
Fusce id diam ac quam ultrices gravida vel nec odio. Maecenas id auctor ipsum. Duis suscipit libero eget diam tempus, id placerat metus porta. In hac habitasse platea dictumst. Proin tortor nulla, consequat at nisi eu, fringilla dictum mauris. In facilisis purus diam, vel vehicula sem porttitor eu. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nullam egestas ut leo sed consectetur.
    </p>,
    <p key  = '6'>
In urna sapien, pellentesque in turpis vel, viverra consequat ipsum. Vestibulum felis nunc, lacinia non odio et, hendrerit placerat eros. Nam dignissim mollis erat non finibus. Pellentesque eu tortor in mauris tristique aliquet. Donec placerat ligula et ultrices venenatis. Nullam posuere, arcu in luctus euismod, tellus erat auctor sem, vitae congue erat ex feugiat lectus. Suspendisse lacinia lacus ut enim laoreet, in mollis mauris elementum. Morbi malesuada, neque sed volutpat maximus, arcu augue porta justo, molestie mattis nisi ipsum non enim. Suspendisse ut venenatis mi, eu fermentum felis. Vestibulum eu feugiat purus. Pellentesque finibus eget neque vitae dapibus. Cras vitae feugiat mi. Mauris venenatis malesuada tortor, quis aliquet neque scelerisque ac.
    </p>,
    <p key  = '7'>
Suspendisse efficitur erat eleifend lacus volutpat, sit amet molestie ipsum luctus. Quisque et magna vitae orci semper varius. Sed in condimentum sem. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam eu lacus luctus, efficitur ipsum ac, dignissim leo. Cras eget ornare est. Vivamus laoreet risus nec tellus auctor, at scelerisque felis facilisis. Cras vel risus quis ante hendrerit fringilla. Cras vel purus tempor risus convallis rutrum ac eu ante. Mauris gravida enim quis orci bibendum varius. Ut id lacinia turpis. Fusce molestie, est nec semper tempor, lacus velit gravida nulla, at tincidunt tellus mauris nec ipsum. Praesent vitae libero odio. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse auctor massa quis risus volutpat lobortis. Donec vel massa turpis.
    </p>,
    <p key  = '8'>
Pellentesque efficitur nec arcu eget dignissim. Maecenas vehicula velit nisl, quis pulvinar massa bibendum id. Nullam finibus leo vitae volutpat imperdiet. Nunc hendrerit pretium suscipit. Sed a blandit metus, at mattis est. Duis quis enim et enim aliquam malesuada nec venenatis lectus. Vestibulum placerat venenatis elit, et malesuada eros vulputate vel.
    </p>,
    <p key  = '9'>
Vivamus molestie consectetur lectus, quis porta libero scelerisque ac. Phasellus ac velit eget tortor pharetra semper. Ut id justo eget massa commodo gravida. Aenean laoreet nec neque ut gravida. Aenean quis felis eu felis efficitur luctus sed et nisi. Mauris nec elit odio. In sit amet tellus ut nulla pulvinar aliquam. Aliquam euismod auctor ex ac malesuada. In pharetra ullamcorper eros, a placerat enim faucibus sit amet. Nam non ante et velit interdum lacinia. Suspendisse eget laoreet dui. Nulla non purus egestas nisl cursus dictum.
    </p>,
    <p key  = '10'>
Pellentesque ipsum nisl, elementum ut faucibus vel, mollis non ligula. Aenean dictum tincidunt bibendum. Donec mollis, velit vitae porttitor bibendum, ipsum dolor malesuada quam, id aliquet tortor lectus et lacus. Vestibulum a interdum enim. Nunc tristique, nisl sed ornare consequat, erat tellus tempor ipsum, id eleifend mauris velit ac libero. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas luctus, orci in fringilla vestibulum, sapien lectus dictum eros, et blandit orci dui at mauris. Etiam rhoncus urna quis nisi blandit rutrum. Praesent condimentum sodales ante. Sed quam eros, ultrices id mollis nec, condimentum at tellus. Vivamus auctor vehicula lectus ac vulputate.
</p>,
]